---
ExternalAddressProviders:
- Uri: https://bot.whatismyipaddress.com/
- Uri: https://ipv4bot.whatismyipaddress.com/
UpdateInterval: 0.00:05:00
DigitalOcean:
  Accounts:
  - Domains:
    - Name: my-example-domain.com
      Records:
      - Name: "@"
        TTL: 30
        Type: A
      - Name: dev
        TTL: 30
        Type: A
      - Name: staging
        TTL: 30
        Type: A
    - Name: my-example-domain.net
      Records:
      - Name: "@"
        TTL: 30
        Type: A
      - Name: dev
        TTL: 30
        Type: A
      - Name: staging
        TTL: 30
        Type: A
    Token: 0e21esbhb6ne6qdbzxjjy266nzltp2pztefk09cfgm64cipb8zaclu6q8c5a3ieg
  - Domains:
    - Name: my-other-example-domain.com
      Records:
      - Name: "@"
        TTL: 30
        Type: A
      - Name: dev
        TTL: 30
        Type: A
      - Name: staging
        TTL: 30
        Type: A
    - Name: my-other-example-domain.com
      Records:
      - Name: "@"
        TTL: 30
        Type: A
      - Name: dev
        TTL: 30
        Type: A
      - Name: staging
        TTL: 30
        Type: A
    Token: 32rzhvtswk5a4amh7ax7hedgkujuupp0cjf5mkqubi6pl6d40ydrywbcw0387b70
