---
version: "3.8"

services:
  ddnsupdate:
    image: ghcr.io/thedanieldoyle/ddnsupdate:latest
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        max_attempts: 10
    volumes:
      - /docker/apps/ddnsupdate/config.json:/app/config.json
      - /docker/apps/ddnsupdate/logs:/app/logs
