name: Test

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
jobs:
  test:
    runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build Project
        run: dotnet build

      - name: Run Tests
        run: dotnet test